### ISSUE TITLE
JSON formatting

### ISSUE THREAD

**Issue by szechy** [lab11/SensorNet-Compiler#3]
The JSON that the Runtime C generation expects: something in the format below, where there is one key "number" giving the number of tables, and then the types of each record in each data table.

As @rohit507 and I have discussed, this should be added to SNC and provided along with C-code upon "compilation".

```
{ "tables": {
    "number": "2",
    "0": [
      { "type": "int" },
      { "type": "string" },
      { "type": "char" },
      { "type": "float" }
    ],
    "1": [
      { "type": "float" },
      { "type": "int" },
      { "type": "char" },
      { "type": "string" }
    ]
  }
}
```

**Comment by rohit507** [comment]
That seems reasonable, though why do you need the key telling you the number of tables? That should probably just be taken from the size of an array of tables.

**Comment by szechy** [comment]
@rohit507: When I first built it, I thought that was a good way to remove complexity initially, based on how the Python JSON parser I was using worked.

**Comment by rohit507** [comment]
Added the json parser as a separate app in the usual place. It just outputs the data to stdout.
